name: flutter_app_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  intl_phone_field: ^3.1.0
  showcaseview: 2.0.3
  mobile_scanner: ^3.3.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/iconBrush.png 
    - assets/images/iconFavorites.png
    - assets/images/iconMove.png  
    - assets/images/Group.png
    - assets/images/Frame.png
    - assets/images/Frame-2.png
    - assets/images/Frame-3.png
    - assets/images/Group-1.png
    - assets/images/Group-2.png
    - assets/images/group-3.png
    - assets/images/group-4.png
    - assets/images/Group-5.png
    - assets/images/Group-6.png
    - assets/images/Group-7.png

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-VariableFont_wdth,wght.ttf
          weight: 600