name: flutter_app_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  intl_phone_field: ^3.1.0
  showcaseview: ^4.0.1
  mobile_scanner: ^3.3.0
  google_maps_flutter: ^2.12.2
  geolocator: ^12.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-VariableFont_wdth,wght.ttf
          weight: 600